In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import os
import numpy as np
import pandas as pd

In [84]:
raw_topic_matrix = np.random.exponential(scale=5, size=(30,15))

In [85]:
raw_topic_matrix

array([[1.62019183e+00, 3.31923685e+00, 6.14979504e+00, 5.06823001e+00,
        4.17210615e+00, 1.15699883e+00, 9.90084919e-01, 2.45586422e+00,
        1.88046321e+00, 2.01260413e+00, 3.65925748e+00, 3.75402335e-02,
        5.21385404e+00, 5.52275794e+00, 4.44746312e+00],
       [8.49125787e+00, 1.85731627e+00, 1.00072553e+01, 1.70067827e+01,
        3.51026480e+00, 8.16559469e+00, 2.43415035e+00, 6.85682206e+00,
        6.37326698e-01, 1.95907653e+00, 8.09908609e-01, 1.08406359e+00,
        1.17689269e+01, 5.08898164e+00, 8.54845587e+00],
       [9.62927702e-01, 1.17730703e-01, 4.89067923e+00, 8.31224748e-01,
        5.34935058e+00, 2.70031933e-01, 6.57906660e+00, 5.66746332e-01,
        1.67103672e+01, 8.35546510e+00, 3.74384944e-01, 2.51790201e-01,
        8.98838974e-02, 9.75441571e+00, 1.53505097e+01],
       [5.00470624e+00, 4.23826076e+00, 1.75853174e+00, 1.58579513e+01,
        1.13512362e+00, 1.88937159e+00, 2.56774635e+00, 6.24132928e-01,
        9.16018744e+00, 4.77796586e+0

In [86]:
normalized_topic_matrix = raw_topic_matrix/np.asarray([np.sum(raw_topic_matrix,axis=1),]*15).transpose()

In [87]:
normalized_topic_matrix

array([[3.39616948e-02, 6.95762730e-02, 1.28909095e-01, 1.06237840e-01,
        8.74537159e-02, 2.42524622e-02, 2.07536918e-02, 5.14786644e-02,
        3.94173804e-02, 4.21872559e-02, 7.67036246e-02, 7.86900620e-04,
        1.09290342e-01, 1.15765440e-01, 9.32256184e-02],
       [9.62441930e-02, 2.10517579e-02, 1.13427271e-01, 1.92763440e-01,
        3.97871091e-02, 9.25529626e-02, 2.75898860e-02, 7.77186745e-02,
        7.22378177e-03, 2.22051601e-02, 9.17991206e-03, 1.22873227e-02,
        1.33394945e-01, 5.76810808e-02, 9.68925040e-02],
       [1.36673553e-02, 1.67101573e-03, 6.94160636e-02, 1.17980238e-02,
        7.59262348e-02, 3.83270972e-03, 9.33802614e-02, 8.04413815e-03,
        2.37179307e-01, 1.18593649e-01, 5.31384861e-03, 3.57379492e-03,
        1.27577092e-03, 1.38449714e-01, 2.17878113e-01],
       [6.64212561e-02, 5.62491762e-02, 2.33388098e-02, 2.10462911e-01,
        1.50650874e-02, 2.50752847e-02, 3.40785112e-02, 8.28334194e-03,
        1.21571802e-01, 6.34120125e-0

In [88]:
raw_query_vector = np.random.exponential(scale=5, size=15)

In [89]:
normalized_query_vector = [float(i)/sum(raw_query_vector) for i in raw_query_vector]

In [90]:
normalized_query_vector

[0.06317056452019308,
 0.18690577458428528,
 0.031582143068541416,
 0.012401379097813844,
 0.12081459159351247,
 0.0015369775285415674,
 0.09221093235912828,
 0.09464528278610788,
 0.03263530233104809,
 0.08755428246473647,
 0.012138452861647503,
 0.06297957110042147,
 0.1027418270036697,
 0.03776989758865906,
 0.06091302111169391]

In [71]:
type(normalized_query_vector)

list

In [91]:
normalized_topic_matrix = pd.DataFrame(normalized_topic_matrix)

In [92]:
normalized_topic_matrix.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [96]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(normalized_topic_matrix, normalized_topic_matrix.index.values)
labels = knn.predict(np.array([normalized_query_vector]))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [102]:
print(labels)

[6]


In [106]:
from sklearn.neighbors import KDTree
tree = KDTree(normalized_topic_matrix)
dist, ind = tree.query(np.array([normalized_query_vector]), k=5)
print(ind)  # indices of 5 closest neighbors
print(dist)  # distances to 5 closest neighbors

[[ 6 16  7 29 26 13  0 25 10 21 27 22  5 17  9]]
[[0.17900779 0.20258463 0.21820075 0.22739451 0.23783301 0.2383166
  0.24250086 0.24687897 0.26207609 0.26581673 0.26757143 0.2698994
  0.2727836  0.27703251 0.27787424]]


In [104]:
pd.DataFrame(normalized_topic_matrix)

0         1         2         3         4         5         6   \
0   0.033962  0.069576  0.128909  0.106238  0.087454  0.024252  0.020754   
1   0.096244  0.021052  0.113427  0.192763  0.039787  0.092553  0.027590   
2   0.013667  0.001671  0.069416  0.011798  0.075926  0.003833  0.093380   
3   0.066421  0.056249  0.023339  0.210463  0.015065  0.025075  0.034079   
4   0.045431  0.016528  0.015143  0.009810  0.043547  0.187829  0.076925   
5   0.102401  0.002215  0.039995  0.048540  0.115624  0.010483  0.125363   
6   0.045354  0.197980  0.081571  0.074399  0.031983  0.052501  0.146700   
7   0.047079  0.113515  0.049856  0.014779  0.015159  0.020975  0.036313   
8   0.001479  0.013066  0.043174  0.527234  0.002684  0.003057  0.087764   
9   0.006044  0.068774  0.009044  0.029045  0.070167  0.146708  0.073430   
10  0.026011  0.070445  0.180253  0.057120  0.084004  0.068040  0.105279   
11  0.047764  0.036669  0.125735  0.030320  0.054559  0.018833  0.018767   
12  0.038859  0.061124  0.046715  0.047046  0.063656  0.057395  0.021974   
13  0.042041  0.027402  0.033290  0.119827  0.094040  0.028973  0.140420   
14  0.034011  0.009476  0.095591  0.039983  0.055456  0.113927  0.049274   
15  0.086657  0.040758  0.265896  0.004745  0.118631  0.078250  0.045850   
16  0.164999  0.239562  0.044476  0.034117  0.080177  0.014208  0.129523   
17  0.036119  0.120287  0.034309  0.133406  0.116014  0.038999  0.063983   
18  0.029279  0.003785  0.011665  0.024526  0.059995  0.167369  0.065819   
19  0.106147  0.069895  0.044832  0.045015  0.001899  0.067378  0.000422   
20  0.083862  0.076690  0.008773  0.193696  0.068343  0.071710  0.003454   
21  0.087958  0.036542  0.017410  0.006180  0.034196  0.051579  0.079360   
22  0.059636  0.041492  0.129752  0.075301  0.093829  0.031593  0.012661   
23  0.028345  0.035440  0.044329  0.061304  0.143547  0.005726  0.010376   
24  0.038639  0.053182  0.008066  0.152378  0.004113  0.054710  0.033029   
25  0.061343  0.149349  0.012794  0.065227  0.158269  0.067714  0.011765   
26  0.101417  0.128051  0.010456  0.051272  0.071370  0.090476  0.080710   
27  0.011369  0.094772  0.207335  0.044320  0.050465  0.080331  0.062151   
28  0.005113  0.008841  0.109902  0.050047  0.091002  0.001368  0.110408   
29  0.108577  0.157209  0.079305  0.038615  0.078014  0.091529  0.017594   

          7         8         9         10        11        12        13  \
0   0.051479  0.039417  0.042187  0.076704  0.000787  0.109290  0.115765   
1   0.077719  0.007224  0.022205  0.009180  0.012287  0.133395  0.057681   
2   0.008044  0.237179  0.118594  0.005314  0.003574  0.001276  0.138450   
3   0.008283  0.121572  0.063412  0.010104  0.044545  0.026815  0.043887   
4   0.040774  0.150205  0.054924  0.112653  0.030806  0.075487  0.030155   
5   0.010647  0.058990  0.007061  0.013386  0.062762  0.241729  0.050116   
6   0.043268  0.046835  0.018695  0.032544  0.039388  0.143605  0.002450   
7   0.069274  0.087908  0.176236  0.076676  0.018095  0.066859  0.123962   
8   0.094593  0.113789  0.013006  0.012250  0.005993  0.007433  0.005355   
9   0.071390  0.002646  0.013246  0.019162  0.026346  0.241120  0.098423   
10  0.017337  0.014155  0.157883  0.059704  0.043897  0.004217  0.046067   
11  0.111506  0.068932  0.011878  0.007369  0.288532  0.085082  0.047950   
12  0.050204  0.015285  0.035006  0.151725  0.070118  0.000863  0.036309   
13  0.035938  0.024324  0.083301  0.098727  0.028931  0.097167  0.027719   
14  0.067451  0.172941  0.078363  0.015618  0.140627  0.062198  0.050188   
15  0.005704  0.048296  0.025998  0.000260  0.081314  0.139446  0.030104   
16  0.016694  0.004465  0.023472  0.103416  0.010726  0.074722  0.033368   
17  0.007004  0.108769  0.025224  0.183465  0.005621  0.035168  0.026883   
18  0.007367  0.049783  0.060732  0.037468  0.005938  0.392135  0.069218   
19  0.085486  0.148929  0.145712  0.130745  0.002233  0.033751  0.113611   
20  0.046361  0.073307  0.041219  0.042617  0.046725  0.0

In [114]:
test = np.zeros(15)
test[2] = 1

In [116]:
from sklearn.neighbors import KDTree
tree = KDTree(normalized_topic_matrix)
dist, ind = tree.query(np.array([test]), k=5)
print(ind)  # indices of 5 closest neighbors
print(dist)  # distances to 5 closest neighbors

[[15 27 10  0 22]]
[[0.77536705 0.82742521 0.86082386 0.91140101 0.91980577]]
