In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
raw_topic_matrix = np.random.exponential(scale=5, size=(30,15))

In [4]:
raw_topic_matrix

array([[1.46911584e+00, 1.00391513e+01, 1.27714887e+01, 6.76882960e-01,
        1.38965363e+01, 2.43441429e+00, 2.13028427e+00, 1.15005672e+01,
        2.55313942e+00, 2.26323894e+01, 9.60383316e+00, 1.90856175e+01,
        1.85997673e+00, 1.09698054e+01, 9.50660826e+00],
       [1.72819474e+01, 5.69951321e-01, 5.13460120e+00, 2.06579662e+00,
        4.80336881e+00, 3.03289080e+00, 4.86632999e+00, 6.31951761e+00,
        9.53176533e+00, 8.08911803e+00, 5.17585966e+00, 4.95612024e-02,
        2.74401191e+00, 4.32250476e+00, 7.83799819e+00],
       [1.06349015e+00, 1.27251049e+00, 1.38041689e+00, 2.14225235e+01,
        3.90918535e+00, 7.26107833e-01, 4.57410879e+00, 2.26366276e+00,
        1.13285722e+01, 1.73405198e+00, 1.51081915e+01, 7.60871473e+00,
        1.29915342e+01, 6.32531932e-01, 1.21339213e-01],
       [8.31825389e+00, 1.12883860e+01, 8.38733661e-01, 5.04767041e+00,
        2.39624476e+00, 3.65763719e+00, 3.66230397e+00, 7.19343084e+00,
        7.40271145e+00, 6.57412304e+0

In [5]:
normalized_topic_matrix = raw_topic_matrix/np.asarray([np.sum(raw_topic_matrix,axis=1),]*15).transpose()

In [6]:
normalized_topic_matrix

array([[1.12035229e-02, 7.65588791e-02, 9.73957687e-02, 5.16193043e-03,
        1.05975417e-01, 1.85649188e-02, 1.62456139e-02, 8.77036817e-02,
        1.94703204e-02, 1.72595303e-01, 7.32391293e-02, 1.45547510e-01,
        1.41842402e-02, 8.36560756e-02, 7.24976892e-02],
       [2.11205626e-01, 6.96547227e-03, 6.27508367e-02, 2.52464527e-02,
        5.87027892e-02, 3.70654756e-02, 5.94722485e-02, 7.72319022e-02,
        1.16489329e-01, 9.88584907e-02, 6.32550634e-02, 6.05695905e-04,
        3.35350374e-02, 5.28260677e-02, 9.57895123e-02],
       [1.23465047e-02, 1.47731097e-02, 1.60258405e-02, 2.48703090e-01,
        4.53833777e-02, 8.42969138e-03, 5.31027537e-02, 2.62798136e-02,
        1.31518161e-01, 2.01313392e-02, 1.75397352e-01, 8.83327711e-02,
        1.50824187e-01, 7.34332937e-03, 1.40867799e-03],
       [8.39569477e-02, 1.13934780e-01, 8.46542062e-03, 5.09466296e-02,
        2.41855321e-02, 3.69168888e-02, 3.69639911e-02, 7.26039989e-02,
        7.47162885e-02, 6.63532649e-0

In [7]:
raw_query_vector = np.random.exponential(scale=5, size=15)

In [8]:
normalized_query_vector = [float(i)/sum(raw_query_vector) for i in raw_query_vector]

In [9]:
normalized_query_vector

[0.09108639226771167,
 0.12155671786635358,
 0.1345507712577825,
 0.11743578223463919,
 0.07121971727465015,
 0.004181359037178592,
 0.016245769671731473,
 0.10792675655313384,
 0.1355726795154853,
 0.025693134491569954,
 0.030599641480233523,
 0.013158555352266062,
 0.03611988210315354,
 0.0016362653696234905,
 0.09301657552448707]

In [10]:
type(normalized_query_vector)

list

In [11]:
normalized_topic_matrix = pd.DataFrame(normalized_topic_matrix)

In [12]:
normalized_topic_matrix.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(normalized_topic_matrix, normalized_topic_matrix.index.values)
labels = knn.predict(np.array([normalized_query_vector]))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [14]:
print(labels)

[1]


In [15]:
from sklearn.neighbors import KDTree
tree = KDTree(normalized_topic_matrix)
dist, ind = tree.query(np.array([normalized_query_vector]), k=5)
print(ind)  # indices of 5 closest neighbors
print(dist)  # distances to 5 closest neighbors

[[11 28  1  3 27]]
[[0.18545094 0.23347044 0.23417662 0.24052093 0.25223389]]


In [16]:
pd.DataFrame(normalized_topic_matrix)

0         1         2         3         4         5         6   \
0   0.011204  0.076559  0.097396  0.005162  0.105975  0.018565  0.016246   
1   0.211206  0.006965  0.062751  0.025246  0.058703  0.037065  0.059472   
2   0.012347  0.014773  0.016026  0.248703  0.045383  0.008430  0.053103   
3   0.083957  0.113935  0.008465  0.050947  0.024186  0.036917  0.036964   
4   0.040385  0.024374  0.083249  0.040612  0.000155  0.168126  0.057699   
5   0.143263  0.052121  0.090657  0.021424  0.003313  0.009632  0.027192   
6   0.004874  0.013988  0.029128  0.054821  0.088038  0.022323  0.005923   
7   0.018857  0.043661  0.114261  0.021857  0.000237  0.052641  0.050946   
8   0.114207  0.025856  0.039225  0.045594  0.015778  0.052139  0.085956   
9   0.054714  0.243641  0.040711  0.065414  0.093763  0.150613  0.006517   
10  0.044340  0.099008  0.005846  0.012597  0.007230  0.035601  0.021107   
11  0.050560  0.032453  0.097906  0.110271  0.008044  0.025688  0.066575   
12  0.022249  0.048713  0.039802  0.064168  0.003788  0.194260  0.022692   
13  0.135543  0.001787  0.023452  0.124110  0.000645  0.060761  0.031990   
14  0.115009  0.036187  0.009101  0.292550  0.014034  0.020738  0.033241   
15  0.040279  0.009194  0.089610  0.075075  0.039004  0.145768  0.000646   
16  0.018453  0.008828  0.139495  0.010866  0.102296  0.059493  0.085033   
17  0.078004  0.031905  0.058730  0.127187  0.037132  0.199235  0.015608   
18  0.182260  0.027351  0.003230  0.122901  0.003376  0.080108  0.141394   
19  0.015246  0.142374  0.064119  0.176322  0.016321  0.154789  0.123434   
20  0.007888  0.045621  0.110411  0.121134  0.061584  0.019567  0.173829   
21  0.058775  0.052051  0.102971  0.028000  0.003750  0.127323  0.036440   
22  0.051512  0.009359  0.049662  0.040268  0.002726  0.281176  0.063027   
23  0.068697  0.026112  0.040201  0.062718  0.132445  0.014069  0.025805   
24  0.023693  0.002730  0.076578  0.039999  0.027219  0.081281  0.028076   
25  0.021315  0.040538  0.027839  0.168939  0.011077  0.000574  0.245186   
26  0.149599  0.009121  0.066548  0.151449  0.018357  0.052072  0.017916   
27  0.123129  0.027743  0.065650  0.084645  0.008348  0.026153  0.082894   
28  0.002590  0.184266  0.062646  0.036346  0.161975  0.084845  0.047478   
29  0.082038  0.094960  0.004078  0.008558  0.013695  0.172343  0.008815   

          7         8         9         10        11        12        13  \
0   0.087704  0.019470  0.172595  0.073239  0.145548  0.014184  0.083656   
1   0.077232  0.116489  0.098858  0.063255  0.000606  0.033535  0.052826   
2   0.026280  0.131518  0.020131  0.175397  0.088333  0.150824  0.007343   
3   0.072604  0.074716  0.066353  0.123892  0.147544  0.045917  0.005321   
4   0.044496  0.005462  0.172364  0.071381  0.065761  0.053477  0.030117   
5   0.000698  0.051368  0.075192  0.040831  0.025018  0.319035  0.035211   
6   0.194541  0.015052  0.015777  0.248217  0.039797  0.067554  0.052794   
7   0.107665  0.122236  0.137886  0.165033  0.004980  0.114972  0.008371   
8   0.023205  0.101371  0.008292  0.025971  0.127065  0.103647  0.055581   
9   0.026069  0.217677  0.024922  0.011640  0.019589  0.015118  0.020159   
10  0.059496  0.046338  0.050177  0.407114  0.047962  0.046301  0.080998   
11  0.035299  0.151407  0.055383  0.055794  0.042213  0.050922  0.082805   
12  0.098848  0.015394  0.119921  0.156630  0.137754  0.025181  0.031621   
13  0.022768  0.045424  0.001489  0.427196  0.016048  0.017681  0.041668   
14  0.023602  0.003689  0.078681  0.006236  0.049716  0.104427  0.134570   
15  0.000165  0.053901  0.074955  0.064972  0.153689  0.155722  0.075141   
16  0.051976  0.068419  0.001409  0.058624  0.262257  0.027347  0.037303   
17  0.083008  0.018886  0.107521  0.008474  0.094990  0.109403  0.009926   
18  0.022918  0.015393  0.009439  0.002109  0.270996  0.065063  0.034841   
19  0.001885  0.013714  0.065643  0.023337  0.031698  0.080127  0.006350   
20  0.062039  0.048074  0.182207  0.038933  0.020286  0.0

In [17]:
test = np.zeros(15)
test[2] = 1

In [18]:
from sklearn.neighbors import KDTree
tree = KDTree(normalized_topic_matrix)
dist, ind = tree.query(np.array([test]), k=5)
print(ind)  # indices of 5 closest neighbors
print(dist)  # distances to 5 closest neighbors

[[16  7 20 21 11]]
[[0.92121154 0.93811462 0.94229721 0.94539434 0.94573786]]


In [19]:
import knn_prediction

In [20]:
knn_prediction.knn_prediction(normalized_topic_matrix,test)

array([[16,  7, 20, 21, 11]])

In [21]:
index = knn_prediction.knn_prediction(normalized_topic_matrix,test)

In [23]:
index.tolist()[0]

[16, 7, 20, 21, 11]

In [24]:
import join_process

In [25]:
join_process.join_process(csv='articles_training.csv',index=index)

Article_index
16    Dylann Roof Himself Rejects Best Defense Again...
7     After ‘The Biggest Loser,’ Their Bodies Fought...
20                                                  NaN
21    Mariah Carey’s Manager Blames Producers for Ne...
11    Can Carbon Capture Technology Prosper Under Tr...
Name: title, dtype: object